---
- name: Disable Galera Cluster Check from Known XInetD Services
  lineinfile:
    path: /etc/services
    insertafter: '^# Local services'
    line: 'mysqlchk    9200/tcp      # MySQL Check'
    state: absent

- name: Uninstall Galera Cluster Check Scripts (XInetD)
  file:
    path: /etc/xinetd.d/mysqlchk
    state: absent

- name: Uninstall Galera Cluster Check Scripts (Binary)
  file:
    path: /usr/bin/clustercheck
    state: absent

- name: Uninstall Galera Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    purge: yes
    state: absent
  with_items:
    - percona-xtradb-cluster-garbd-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-common-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-server-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-client-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-galera-3.x
    - percona-xtrabackup-24
  when:
    - galera_distribution == 'percona'

- name: Uninstall Galera Repository
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    purge: yes
    state: absent
  with_items:
    - percona-release
  when:
    - galera_distribution == 'percona'
